// Writes a GitHub Actions workflow that benchmarks every pull request against its base commit:
// both run on fresh dev servers side by side, the scenarios replay in headless Chrome under the
// device profiles, and the comparison goes to the job summary, with the full report and traces
// uploaded as an artifact.
import { posix } from 'node:path';

export const TOOL_REPO = 'https://github.com/jaypatel1210/react-best-practices.git';
const ACTIONS = {
  checkout: 'actions/checkout@v7',
  setupNode: 'actions/setup-node@v7',
  uploadArtifact: 'actions/upload-artifact@v7',
  pnpm: 'pnpm/action-setup@v6',
  bun: 'oven-sh/setup-bun@v2',
};

const INSTALL = {
  pnpm: 'pnpm install --frozen-lockfile',
  npm: 'npm ci',
  yarn: 'yarn install --frozen-lockfile',
  'yarn-berry': 'yarn install --immutable',
  bun: 'bun install --frozen-lockfile',
};

function quote(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function shellQuote(value) {
  return `"${String(value).replace(/(["\\$`])/g, '\\$1')}"`;
}

function rel(path) {
  const clean = posix.normalize(String(path || '.').replace(/\\/g, '/')).replace(/\/$/, '');
  if (clean.startsWith('..') || clean.startsWith('/')) throw new Error(`Paths must be relative to the repository root (got "${path}")`);
  return clean === '' ? '.' : clean;
}

/**
 * options: app (app folder, relative to the repository root), scenarios (files, relative to the
 * root), dev (dev command with {port}), devCwd (where to run it; default the app folder),
 * packageManager (pnpm | npm | yarn | yarn-berry | bun), pnpmVersion (when package.json doesn't
 * declare one), install (override), profiles, portA, portB, paths (trigger filters), toolRef,
 * failOn ('slower' | 'no-gain' | 'none'), maxPairs, node, timeoutMinutes, replay.
 */
export function ciWorkflow(options) {
  const {
    app = '.',
    scenarios = [],
    dev,
    devCwd,
    packageManager = 'npm',
    pnpmVersion,
    install,
    profiles = 'mobile,desktop',
    portA = 4100,
    portB = 4200,
    paths = [],
    toolRef = 'main',
    failOn = 'slower',
    maxPairs,
    node = 'lts/*',
    timeoutMinutes = 90,
    replay = true,
  } = options;
  if (!dev || !dev.includes('{port}')) throw new Error('--dev must be the dev command with {port} where the port goes, e.g. "pnpm dev -- --port {port}"');
  if (!scenarios.length) throw new Error('Pass the scenario files to replay (--scenario), committed in the repository');
  if (!INSTALL[packageManager]) throw new Error(`Unknown package manager "${packageManager}" (${Object.keys(INSTALL).join(', ')})`);
  const appDir = rel(app);
  const runDir = rel(devCwd || app);
  const join = (base, dir) => (dir === '.' ? base : `${base}/${dir}`);

  const y = [];
  y.push('# Generated by react-render-audit (`render-audit ci`). For every pull request it starts the base');
  y.push('# commit and the pull request side by side on fresh dev servers, replays the scenarios in');
  y.push('# headless Chrome under fixed device profiles, and writes the timing comparison to the job');
  y.push('# summary. The full benchmark (raw runs and Chrome traces) is uploaded as an artifact.');
  y.push('# Shared runners are noisier than a laptop: the benchmark measures that noise first and runs');
  y.push('# more pairs, or reports "no measurable change", rather than guessing.');
  y.push('name: Render benchmark');
  y.push('');
  y.push('on:');
  y.push('  pull_request:');
  if (paths.length) {
    y.push('    paths:');
    for (const path of paths) y.push(`      - ${quote(path)}`);
  }
  y.push('');
  y.push('permissions:');
  y.push('  contents: read');
  y.push('');
  y.push('concurrency:');
  y.push('  group: render-benchmark-${{ github.event.pull_request.number }}');
  y.push('  cancel-in-progress: true');
  y.push('');
  y.push('jobs:');
  y.push('  benchmark:');
  y.push('    runs-on: ubuntu-latest');
  y.push(`    timeout-minutes: ${timeoutMinutes}`);
  y.push('    steps:');
  y.push(`      - uses: ${ACTIONS.checkout}`);
  y.push('        with:');
  y.push('          fetch-depth: 0');
  if (packageManager === 'pnpm') {
    y.push(`      - uses: ${ACTIONS.pnpm}`);
    if (pnpmVersion) {
      y.push('        with:');
      y.push(`          version: ${quote(pnpmVersion)}`);
    }
  }
  if (packageManager === 'bun') y.push(`      - uses: ${ACTIONS.bun}`);
  y.push(`      - uses: ${ACTIONS.setupNode}`);
  y.push('        with:');
  y.push(`          node-version: ${quote(node)}`);
  if (packageManager === 'pnpm' || packageManager === 'npm') y.push(`          cache: ${packageManager}`);
  if (packageManager.startsWith('yarn')) {
    y.push('      - name: Enable Corepack (Yarn)');
    y.push('        run: corepack enable');
  }
  y.push('      - name: Install dependencies');
  y.push(`        run: ${install || INSTALL[packageManager]}`);
  y.push('      - name: Get react-render-audit');
  y.push('        run: |');
  y.push(`          git clone --filter=blob:none ${TOOL_REPO} "$RUNNER_TEMP/react-best-practices"`);
  y.push(`          git -C "$RUNNER_TEMP/react-best-practices" checkout --detach ${shellQuote(toolRef)}`);
  y.push('          echo "RA=$RUNNER_TEMP/react-best-practices/plugins/react-render-audit/skills/optimize-renders/scripts/render-audit.mjs" >> "$GITHUB_ENV"');
  y.push('      - name: Check out and install the base commit');
  y.push(`        run: node "$RA" baseline --root ${shellQuote(appDir)} --ref "\${{ github.event.pull_request.base.sha }}" --dir "$RUNNER_TEMP/baseline" --audit "$RUNNER_TEMP/audit"${install ? ` --install ${shellQuote(install)}` : ''}`);
  y.push('      - name: Benchmark the base commit against the pull request');
  y.push('        run: >-');
  y.push('          node "$RA" bench --audit "$RUNNER_TEMP/audit" --label pull-request');
  for (const scenario of scenarios) y.push(`          --scenario ${shellQuote(rel(scenario))}`);
  y.push(`          --a http://localhost:${portA} --a-label base --a-cmd ${shellQuote(dev)} --a-cwd "${join('$RUNNER_TEMP/baseline', runDir)}"`);
  y.push(`          --b http://localhost:${portB} --b-label pull-request --b-cmd ${shellQuote(dev)} --b-cwd "${join('$GITHUB_WORKSPACE', runDir)}"`);
  y.push(`          --profiles ${profiles}${maxPairs ? ` --max-pairs ${Number(maxPairs)}` : ''}${replay ? '' : ' --no-replay'} --markdown "$GITHUB_STEP_SUMMARY"${failOn && failOn !== 'none' ? ` --fail-on ${failOn}` : ''}`);
  y.push('      - name: Upload the benchmark');
  y.push('        if: always()');
  y.push(`        uses: ${ACTIONS.uploadArtifact}`);
  y.push('        with:');
  y.push('          name: render-benchmark');
  y.push('          path: ${{ runner.temp }}/audit');
  y.push('          if-no-files-found: ignore');
  return `${y.join('\n')}\n`;
}
